# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d7c39526d61258c1dccba73ae94fceac9377c579ec9573698ed8f732c727b0cad8e33f7b9117dea8404f7e928d5f1c4c19173fa4d938c1c15c2609f5afd0035

test:
  secret_key_base: 8e2ebe77ba2911ea285ccba28d505d352c9248bc116e234987449477a87ccd3119ef9b924bf7677d1158479d2f0fae9dbc8b1ede64fd2857f40d289ae3bd9f67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
